import React from 'react';
import { connect } from 'react-redux';
import GoogleMaps from '../google-energy-map/GoogleMap';

import { MapBubble } from '../../../../external/react-d3-bubble/index';
import FilterBox from './FilterBox';
import { getSourceCssName, getProducerDisplayname, getSourceDisplayname } from '../../utils/nameMaps.js';

const width = 960;
const height = 700;

// Keep these names as they map to the fields in Map json.
const sources = ['coal', 'hydroelectric', 'wind', 'naturalGas', 'petroleum', 'solar', 'nuclear'];
const sourceButtonBorders = ['red', 'blue', 'lightgrey', 'orange', 'black', 'yellow', 'green'];
const utilities = ['IPP CHP', 'IPP Non-CHP', 'Electric Utility'];

const domain = {
    scale: 'sqrt',
    domain: [0, 2000],
    range: [0, 15]
};

@connect((store, props) => {
	return {
        allPlants: store.usEnergyMap.allPlants
	};
})
export default class EnergySourceMapHoc extends React.Component {

    componentDidMount() {
        if(this.props.showMap) {
            return true;
        };
        console.log('Getting US Energy Data');
        fetch('/api/get-all-energy-sources')  
            .then(res => res.json())
            .then(sources => {
                console.log(sources.length);
                const nonZero = sources.filter(source => source.total > 100);
                console.log('nonZero', nonZero.length);
                const hasPrimary = nonZero.filter(source => source.primaryFuel);
                console.log('hasPrimary', hasPrimary.length);
                
                console.log('example: ', hasPrimary[33]);
                
                this.props.dispatch({ type: 'LOADED_ENERGY_PLANTS', payload: hasPrimary })
            });
    };


  render() {
      const startingCoords = { lat: 37.0902, lng: -95.7129};
      const maxDistance = 2200;
    
    return (
        <div className="us-energy-map-container">
            <b>Energy generated by source</b>
            <br />
            This interactive map shows the location, output (MWHs/year), and type of electricity generated in the US.
            <br />
            This includes both private and public active power stations in the US as of April 2017 (source: <a href="https://www.eia.gov/electricity/data/eia860m/">EIA</a>)
            
            <div>
                <GoogleMaps
                    circlesToRender={this.props.allPlants}
                    maxDistance={maxDistance}
                    startingCoords={startingCoords}
                    sizeMultiplier={15000}
                />
            </div>
        </div>
    )
  }
}  