// Thile file turns magic strings into magic ids!

export default {
    never: 'Never',
    justToAndFromWork: 'Just to and from work',
    mostOfTheTime: 'Most of the time',
    always: 'Always',
    rarely: 'Rarely',
    fewTimesPerDay: 'Few times per day',
    asMuchAsPossible: 'As much as possible',
    onceADay: 'Once a day',
    onceAWeek: 'Once a week',
    onceAMonth: 'Once a month',
    mostNights: 'Most nights',
    underOnceAWeek: 'Less than once a week',
    twoThreeTimesPerWeek: '2-3 times per week',
    fewTimesPerMonth: 'A few times per month',
    everyday: 'Everyday',
    wood: 'Wood',
    gasVents: 'Gas Vents',
    radiantFloors: 'Radiant floors',
    heatPump: 'Heat pump',
    radiator: 'Radiator',
    reasonableInsulated: 'Reasonably Insulated',
    extremelyInsulated: 'Extremely Insulated',
    somewhatInsulated: 'Somewhat Insulated',
    poorlyInsulated: 'Poorly Insulated',
    standard: 'Standard',
    apartment: 'Apartment',
    veryLittleFurniture: 'I have almost no furniture',
    practicallyEmpty: 'Practically empty',
    quiteUncluttered: 'Quite uncluttered',
    justTheEssentials: 'Just the essentials',
    spareslyFurnished: 'My rooms are sparesly furnished',
    reasonablyFull: 'Reasonably full',
    aGoodAmount: 'A good amount',
    hardlyAny: 'Hardly any',
    allTheEssentials: 'I have all of the essentials',
    extremelyFull: 'Extremely full',
    packedCloset: 'My closet is packed',
    house: 'House',
    crampedHome: 'My home is cramped',
    noRoom: 'There\'s no more room',
    wayTooMany: 'Way too many',
    sixteenNineteen: '16-19',
    twentyThirtyFour: '20-34',
    thirtyFiveFiftyFour: '35-54',
    fiftyFiveSixtyFour: '55-64',
    sixtyFivePlus: '65+',
    americanAverage: 'American Average',
    underThirtyK: 'Under $30k',
    thirtySixtyK: '$30k-$60k',
    sixtyOneHundredK: '$60k-$100k',
    overOneHundredK: 'Over $100k',
    gasoline: 'Gasoline',
    diesel: 'Diesel',
    electricity: 'Electricity',
    centralAc: 'Central AC',
    windowMountAc: 'Window Mount AC',
    lotsOfFans: 'Lots of Fans',
    none: 'None',
    dog: 'Dog',
    cat: 'Cat',
    noIdea: 'No Idea',
    under100Miles: 'Under 100 miles',
    oneHundredTwoHundredMiles: '100-200 miles',
    over200Miles: 'Over 200 miles',
    house: 'House',
    apartment: 'Apartment',
    brick: 'Brick',
    wood: 'Wood',
    concrete: 'Concrete',
    entireHome: 'Entire home',
    someRooms: 'Some rooms',
    justCurrentRoom: 'Just my current room',
    mostRooms: 'Most rooms',
    halfOfRooms: 'Half of rooms',
    quarterOfRooms: 'Quarter of rooms',
    midsizeSuv: 'Midsize SUV',
    lightweight: 'Lightweight',
    standard: 'Standard',
    luxurious: 'Luxurious',
    rugged: 'Rugged' ,
    smartCar: 'Smart car',
    compactCar: 'Compact car',
    midsizeCar: 'Midsize car',
    largeCar: 'Large car',
    compactSuv: 'Compact SUV',
    largeSuv: 'Large SUV',
    compactTruck: 'Compact truck',
    midsizeTruck: 'Midsize truck',
    largeTruck: 'Large truck'

}