// Thile file turns magic strings into magic ids!

export default {
    onceADay: 'Once a day',
    onceAWeek: 'Once a week',
    onceAMonth: 'Once a month',
    mostNights: 'Most nights',
    underOnceAWeek: 'Less than once a week',
    twoThreeTimesPerWeek: '2-3 times per week',
    midsizeCar: 'Midsize car',
    wood: 'Wood',
    gasVents: 'Gas Vents',
    reasonableInsulated: 'Reasonably Insulated',
    compactCar: 'Compact car',
    standard: 'Standard',
    apartment: 'Apartment',
    veryLittleFurniture: 'I have almost no furniture',
    practicallyEmpty: 'Practically empty',
    justTheEssentials: 'Just the essentials',
    spareslyFurnished: 'My rooms are sparesly furnished',
    reasonablyFull: 'Reasonably full',
    aGoodAmount: 'A good amount',
    allTheEssentials: 'I have all of the essentials',
    extremelyFull: 'Extremely full',
    packedCloset: 'My closet is packed',
    midsizeSuv: 'Midsize SUV',
    luxurious: 'Luxurious',
    house: 'House',
    crampedHome: 'My home is cramped',
    noRoom: 'There\'s no more room',
    wayTooMany: 'Way too many',
    largeSuv: 'Large SUV',
    sixteenNineteen: '16-19',
    twentyThirtyFour: '20-34',
    thirtyFiveFiftyFour: '35-54',
    fiftyFiveSixtyFour: '55-64',
    sixtyFivePlus: '65+',
    americanAverage: 'American Average',
    underThirtyK: 'Under $30k',
    thirtySixtyK: '$30k-$60k',
    sixtyOneHundredK: '$60k-$100k',
    overOneHundredK: 'Over $100k',
    gasoline: 'Gasoline',
    justToAndFromWork: 'Just to and from work',
    centralAc: 'Central AC',
    dog: 'Dog',
    cat: 'Cat',
    noIdea: 'No Idea',
    under100Miles: 'Under 100 miles',
    oneHundredTwoHundredMiles: '100-200 miles',
    over200Miles: 'Over 200 miles',
    house: 'House',
    apartment: 'Apartment',
    brick: 'Brick',
    wood: 'Wood',
    concrete: 'Concrete'

}